### PR TITLE
Add support for Github enterprise repositories

### PR DESCRIPTION
**Pull request by d1egoaz**
Add support for Github enterprise repositories as hostnames are different than github.com.

This is my first time writing LISP code, so I hope I'm not doing something crazy here.

### CODE REVIEW

**Comment by diego-alvarez-hs** [comment]
Ping @osener

**Comment by ozanvos** [comment]
@diego-alvarez-hs sorry for taking so long to review this. I see you're taking the full url from `remote.origin.url` but I think more often than not non-github values will point to something like Bitbucket rather than a Github Enterprise repo. 

What do you think about introducing a local variable such as `github-browse-file--github-enterprise-root` and using it instead of github.com if it's non-nil?

/cc @dgtized, @wjlroe, and  @waymondo as you guys are probably more familiar with this package than I am at this point, and hopefully have experience with Github Enterprise :)

**Comment by d12frosted** [comment]
Also, relying on `remote.origin.url` is not really good, because `origin` is optional name.

**Comment by slackorama** [comment]
I took a stab at adding support for github enterprise and bitbucket...as well as the non-origin remotes.

**Comment by jjrussell** [comment]
I think I just wrote almost the same thing. Should have checked for existing PRs I guess #facepalm
https://github.com/osener/github-browse-file/pull/26

**Pull request closed without merging**
